ci: Handle errors in mdbook.

diff --git a/.github/workflows/deploy-book.yml b/.github/workflows/deploy-book.yml
--- a/.github/workflows/deploy-book.yml
+++ b/.github/workflows/deploy-book.yml
@@ -28,9 +28,10 @@ jobs:
           echo `pwd`/mdbook >> $GITHUB_PATH
       - name: Build Book
         run: |
-          # This assumes your book is in the root of your repository.
-          # Just add a `cd` here if you need to change to another directory.
-          mdbook build ./pywr-book
+          output=$(mdbook build ./pywr-book 2>&1)
+          if echo "$output" | grep -q "\[ERROR\]" ; then
+              exit 1
+          fi
       - name: Setup Pages
         uses: actions/configure-pages@v5
       - name: Upload artifact
